name: CI

on: 
  push:
    paths:
    - '**.cc'
    - '**.h'
    - '**Tupfile'
    - 'Tuprules.tup'
    - '.github/workflows/CI.yml'
  pull_request:
    paths:
    - '**.cc'
    - '**.h'
    - '**Tupfile'
    - 'Tuprules.tup'
    - '.github/workflows/CI.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install tup build system
        run: |
          sudo apt-get -q -y install libfuse3-dev
          cd ..
          git clone git://github.com/gittup/tup.git
          cd tup
          ./bootstrap.sh
          cd ../FacadeUI

      - name: Update submodules
        run: |
          git submodule init
          git submodule update

      - name: Run tup to build
        run: ../tup/tup
        
      - name: Run tests
        run: test/facade_test
