name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install tup build system
        run: |
          sudo apt -q -y install libfuse3-dev
          git clone git://github.com/gittup/tup.git
          cd tup
          ./bootstrap.sh

      - name: Run tup to build
        run: tup/tup
        
      - name: Run tests
        run: test/facade_test
